//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Cars: [
      { speed: 1, colour: 'colour 1', id: 65 },
      { speed: 2, colour: 'colour 2', id: 75 },
      { speed: 3, colour: 'colour 3', id: 29 },
      { speed: 4, colour: 'colour 4', id: 40 },
      { speed: 5, colour: 'colour 5', id: 52 },
    ],
  },
};
export default data;
